name = "Origins Modpack"
author = "Zainothy"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3aa8ea7b9a8330f7e30fdbd0de8053bf8e76da5bc796790fb85ebcc4d97091cf"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
