name = "SimpleOrigins"
author = "Zainothy"
version = "10.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "262264123d0bb61166ddd7918c2b0be74e76189cf6ab56baad8ac6f27dd7209f"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
