name = "Origins Modpack"
author = "Zainothy"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "905b886f86c58760ce0cdc0893eabc09f29526fc9d810458fb96138628ebab5c"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
