name = "Origins Modpack"
author = "Zainothy"
version = "6.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "967d6a39442e50b73e53f9e9dd77c65c97546dea2fb15f195f748b9796735c88"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
